# Generated by Django 5.2.17 on 2026-09-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True), ("used_at__isnull", True)),
                fields=("workspace", "email"),
                name="one_pending_invitation_per_email",
            ),
        ),
    ]
