# Generated by Django 5.2.17 on 2026-10-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invitation_one_pending_invitation_per_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
