from django.contrib import admin
from django.urls import path
from drf_spectacular.views import SpectacularAPIView

from accounts.views import (
    CsrfView,
    InvitationCreateView,
    InvitationRevokeView,
    InviteAcceptView,
    InvitePreviewView,
    LoginView,
    LogoutView,
    MembershipListView,
    MembershipPasswordResetView,
    MembershipRevokeView,
    MembershipRoleView,
    PasswordResetPreviewView,
    PasswordResetRedeemView,
    SessionView,
)
from connections.views import (
    CallbackView,
    ChannelView,
    ConnectionListView,
    DisconnectView,
    GitHubWebhookView,
    RefreshView,
    ReportDeleteView,
    ReportPermalinkRetryView,
    SetupView,
    SlackEventsView,
    SlackIdentityView,
    SlackInteractionsView,
    SlackLinkCodeView,
    SlackUnlinkView,
    WorkspaceDeleteView,
)
from feedback.views import (
    FollowUpDetailView,
    FollowUpListView,
    FollowUpNotificationApproveView,
    FollowUpNotificationCancelView,
    FollowUpNotificationDraftView,
    FollowUpNotificationEditView,
    FollowUpNotificationMarkDeliveredView,
    FollowUpNotificationSendAgainView,
    FollowUpOutcomeCorrectView,
    FollowUpOutcomeView,
    FollowUpRecipientView,
    MemberDirectoryView,
    ProblemActivityListView,
    ProblemDetailView,
    ProblemEditView,
    ProblemExternalOperationView,
    ProblemFixConfirmationView,
    ProblemFixReleaseLinkView,
    ProblemFixReleaseUnlinkView,
    ProblemIssueAbandonView,
    ProblemIssueApproveView,
    ProblemIssueLinkView,
    ProblemIssuePreviewView,
    ProblemIssueRecoveryView,
    ProblemIssueRefreshView,
    ProblemListView,
    ProblemOwnerView,
    ProblemReportListView,
    ReportAssignView,
    ReportConfirmFixAppliesView,
    ReportCreateProblemView,
    ReportDetailView,
    ReportDismissView,
    ReportLinkView,
    ReportListView,
    ReportRestoreView,
    ReportUnlinkView,
    WorkspaceReleaseListView,
)
from health.views import LiveView, ReadyView
from matching.views import (
    ReportMatchRetryView,
    ReportMatchView,
    SuggestionAcceptView,
    SuggestionRejectView,
)

urlpatterns = [
    path(
        "api/workspaces/<uuid:workspace_id>/releases/",
        WorkspaceReleaseListView.as_view(),
        name="workspace-releases",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/problems/<uuid:problem_id>/fix-release/",
        ProblemFixReleaseLinkView.as_view(),
        name="problem-fix-release-link",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/problems/<uuid:problem_id>/fix-release/unlink/",
        ProblemFixReleaseUnlinkView.as_view(),
        name="problem-fix-release-unlink",
    ),
    path("api/workspaces/<uuid:workspace_id>/connections/", ConnectionListView.as_view()),
    path(
        "api/workspaces/<uuid:workspace_id>/connections/<str:provider>/setup/", SetupView.as_view()
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/connections/<str:provider>/callback/",
        CallbackView.as_view(),
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/connections/<str:provider>/disconnect/",
        DisconnectView.as_view(),
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/connections/<str:provider>/refresh/",
        RefreshView.as_view(),
    ),
    path("api/workspaces/<uuid:workspace_id>/channels/", ChannelView.as_view()),
    path("api/workspaces/<uuid:workspace_id>/delete/", WorkspaceDeleteView.as_view()),
    path(
        "api/workspaces/<uuid:workspace_id>/slack/identity/",
        SlackIdentityView.as_view(),
        name="slack-identity",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/slack/identity/unlink/",
        SlackUnlinkView.as_view(),
        name="slack-unlink",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/slack/link-code/",
        SlackLinkCodeView.as_view(),
        name="slack-link-code",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/reports/<uuid:report_id>/confirm-fix-applies/",
        ReportConfirmFixAppliesView.as_view(),
        name="report-confirm-fix-applies",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/reports/<uuid:report_id>/delete/",
        ReportDeleteView.as_view(),
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/reports/<uuid:report_id>/permalink/retry/",
        ReportPermalinkRetryView.as_view(),
        name="report-permalink-retry",
    ),
    path(
        "api/integrations/slack/interactions/",
        SlackInteractionsView.as_view(),
        name="slack-interactions",
    ),
    path("api/integrations/slack/events/", SlackEventsView.as_view(), name="slack-events"),
    path(
        "api/integrations/github/webhook/",
        GitHubWebhookView.as_view(),
        name="github-webhook",
    ),
    path("admin/", admin.site.urls),
    path("api/health/live/", LiveView.as_view(), name="health-live"),
    path("api/health/ready/", ReadyView.as_view(), name="health-ready"),
    path("api/auth/login/", LoginView.as_view(), name="auth-login"),
    path("api/auth/csrf/", CsrfView.as_view(), name="auth-csrf"),
    path("api/auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("api/auth/session/", SessionView.as_view(), name="auth-session"),
    path("api/invitations/preview/", InvitePreviewView.as_view(), name="invitation-preview"),
    path("api/invitations/accept/", InviteAcceptView.as_view(), name="invitation-accept"),
    path(
        "api/password-resets/preview/",
        PasswordResetPreviewView.as_view(),
        name="password-reset-preview",
    ),
    path(
        "api/password-resets/redeem/",
        PasswordResetRedeemView.as_view(),
        name="password-reset-redeem",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/invitations/",
        InvitationCreateView.as_view(),
        name="invitation-create",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/invitations/<uuid:invitation_id>/revoke/",
        InvitationRevokeView.as_view(),
        name="invitation-revoke",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/memberships/",
        MembershipListView.as_view(),
        name="membership-list",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/memberships/<uuid:membership_id>/revoke/",
        MembershipRevokeView.as_view(),
        name="membership-revoke",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/memberships/<uuid:membership_id>/role/",
        MembershipRoleView.as_view(),
        name="membership-role",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/memberships/<uuid:membership_id>/password-reset/",
        MembershipPasswordResetView.as_view(),
        name="membership-password-reset",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/members/",
        MemberDirectoryView.as_view(),
        name="member-directory",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/reports/",
        ReportListView.as_view(),
        name="report-list",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/reports/<uuid:report_id>/",
        ReportDetailView.as_view(),
        name="report-detail",
    ),
    *[
        path(
            f"api/workspaces/<uuid:workspace_id>/reports/<uuid:report_id>/{action}/",
            view,
            name=name,
        )
        for action, view, name in (
            ("link", ReportLinkView.as_view(), "report-link"),
            ("create-problem", ReportCreateProblemView.as_view(), "report-create-problem"),
            ("unlink", ReportUnlinkView.as_view(), "report-unlink"),
            ("dismiss", ReportDismissView.as_view(), "report-dismiss"),
            ("restore", ReportRestoreView.as_view(), "report-restore"),
            ("assign", ReportAssignView.as_view(), "report-assign"),
        )
    ],
    path(
        "api/workspaces/<uuid:workspace_id>/follow-ups/",
        FollowUpListView.as_view(),
        name="follow-up-list",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/follow-ups/<uuid:follow_up_id>/",
        FollowUpDetailView.as_view(),
        name="follow-up-detail",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/follow-ups/<uuid:follow_up_id>/notification/",
        FollowUpNotificationDraftView.as_view(),
        name="follow-up-notification-draft",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/follow-ups/<uuid:follow_up_id>/notification/edit/",
        FollowUpNotificationEditView.as_view(),
        name="follow-up-notification-edit",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/follow-ups/<uuid:follow_up_id>/notification/approve/",
        FollowUpNotificationApproveView.as_view(),
        name="follow-up-notification-approve",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/follow-ups/<uuid:follow_up_id>/notification/mark-delivered/",
        FollowUpNotificationMarkDeliveredView.as_view(),
        name="follow-up-notification-mark-delivered",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/follow-ups/<uuid:follow_up_id>/notification/send-again/",
        FollowUpNotificationSendAgainView.as_view(),
        name="follow-up-notification-send-again",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/follow-ups/<uuid:follow_up_id>/notification/cancel/",
        FollowUpNotificationCancelView.as_view(),
        name="follow-up-notification-cancel",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/follow-ups/<uuid:follow_up_id>/outcome/",
        FollowUpOutcomeView.as_view(),
        name="follow-up-outcome",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/follow-ups/<uuid:follow_up_id>/outcome/correct/",
        FollowUpOutcomeCorrectView.as_view(),
        name="follow-up-outcome-correct",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/follow-ups/<uuid:follow_up_id>/recipient/",
        FollowUpRecipientView.as_view(),
        name="follow-up-recipient",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/problems/",
        ProblemListView.as_view(),
        name="problem-list",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/problems/<uuid:problem_id>/",
        ProblemDetailView.as_view(),
        name="problem-detail",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/problems/<uuid:problem_id>/confirm-fix/",
        ProblemFixConfirmationView.as_view(),
        name="problem-confirm-fix",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/problems/<uuid:problem_id>/reports/",
        ProblemReportListView.as_view(),
        name="problem-reports",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/problems/<uuid:problem_id>/activity/",
        ProblemActivityListView.as_view(),
        name="problem-activity",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/problems/<uuid:problem_id>/edit/",
        ProblemEditView.as_view(),
        name="problem-edit",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/problems/<uuid:problem_id>/assign-owner/",
        ProblemOwnerView.as_view(),
        name="problem-assign-owner",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/problems/<uuid:problem_id>/issue/link/",
        ProblemIssueLinkView.as_view(),
        name="problem-issue-link",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/problems/<uuid:problem_id>/issue/preview/",
        ProblemIssuePreviewView.as_view(),
        name="problem-issue-preview",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/problems/<uuid:problem_id>/issue/approve/",
        ProblemIssueApproveView.as_view(),
        name="problem-issue-approve",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/problems/<uuid:problem_id>/issue/operations/<uuid:operation_id>/",
        ProblemExternalOperationView.as_view(),
        name="problem-issue-operation",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/problems/<uuid:problem_id>/issue/operations/<uuid:operation_id>/abandon/",
        ProblemIssueAbandonView.as_view(),
        name="problem-issue-abandon",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/problems/<uuid:problem_id>/issue/operations/<uuid:operation_id>/reconcile/",
        ProblemIssueRecoveryView.as_view(),
        name="problem-issue-operation-reconcile",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/problems/<uuid:problem_id>/issue/refresh/",
        ProblemIssueRefreshView.as_view(),
        name="problem-issue-refresh",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/reports/<uuid:report_id>/match/",
        ReportMatchView.as_view(),
        name="report-match",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/reports/<uuid:report_id>/match/retry/",
        ReportMatchRetryView.as_view(),
        name="report-match-retry",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/match-suggestions/<uuid:suggestion_id>/accept/",
        SuggestionAcceptView.as_view(),
        name="match-suggestion-accept",
    ),
    path(
        "api/workspaces/<uuid:workspace_id>/match-suggestions/<uuid:suggestion_id>/reject/",
        SuggestionRejectView.as_view(),
        name="match-suggestion-reject",
    ),
    path("api/schema/", SpectacularAPIView.as_view(authentication_classes=[]), name="schema"),
]
