# Generated by Django 5.2.17 on 2026-09-28 19:46

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_invitation_one_pending_invitation_per_email"),
        ("connections", "0003_connection_binding_revision"),
        ("feedback", "0007_engineeringissue_connection_binding_revision_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(choices=[("github", "GitHub")], max_length=16)),
                ("delivery_id", models.CharField(max_length=128)),
                ("event", models.CharField(max_length=64)),
                ("action", models.CharField(blank=True, max_length=64)),
                ("installation_id", models.CharField(blank=True, max_length=64)),
                ("repository_id", models.CharField(blank=True, max_length=64)),
                ("issue_id", models.CharField(blank=True, max_length=64)),
                ("normalized", models.JSONField(default=dict)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("provider_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("retry_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("safe_error", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "indexes": [models.Index(fields=["status", "retry_at"], name="receipt_due_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "delivery_id"), name="unique_inbound_delivery"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ExternalOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("github_issue_create", "Create GitHub issue")], max_length=32
                    ),
                ),
                ("action_key", models.UUIDField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("uncertain", "Uncertain"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("body", models.TextField(max_length=10000)),
                ("destination", models.CharField(max_length=200)),
                ("problem_version", models.PositiveIntegerField()),
                ("binding_revision", models.PositiveIntegerField()),
                ("draft_version", models.PositiveIntegerField(default=1)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("due_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("remote_issue_id", models.CharField(blank=True, max_length=64)),
                ("remote_number", models.PositiveIntegerField(blank=True, null=True)),
                ("remote_url", models.URLField(blank=True, max_length=500)),
                ("safe_error", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="connections.connection"
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="feedback.problem"
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="accounts.membership"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.workspace"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["state", "due_at"], name="external_operation_due_idx"),
                    models.Index(
                        fields=["workspace", "problem", "state"], name="external_op_problem_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "action_key"), name="operation_workspace_action_key"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("state__in", ["queued", "running", "uncertain"])),
                        fields=("problem",),
                        name="one_unresolved_issue_create_per_problem",
                    ),
                ],
            },
        ),
    ]
