# Generated by Django 5.2.17 on 2026-10-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inboundreceipt",
            name="provider",
            field=models.CharField(
                choices=[("github", "GitHub"), ("slack", "Slack")], max_length=16
            ),
        ),
    ]
