# Generated by Django 5.2.17 on 2026-09-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaloperation",
            name="recovery_reference",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
