# Generated by Django 5.2.17 on 2026-09-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0002_externaloperation_recovery_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaloperation",
            name="repository_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
