# Generated by Django 5.2.17 on 2026-09-28 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_invitation_one_pending_invitation_per_email"),
        ("operations", "0003_externaloperation_repository_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaloperation",
            name="recovery_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="externaloperation",
            name="recovery_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="externaloperation",
            name="resolution_reason",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="externaloperation",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resolved_issue_operations",
                to="accounts.membership",
            ),
        ),
    ]
