# Generated by Django 5.2.17 on 2026-10-04 14:28

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_invitation_one_pending_invitation_per_email"),
        ("feedback", "0009_follow_up_delivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("report_version", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("ranked", "Ranked"),
                            ("abstained", "Abstained"),
                            ("failed", "Failed"),
                            ("stale", "Stale"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "failure",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("retrieval_failed", "retrieval_failed"),
                            ("invalid_request", "invalid_request"),
                            ("unsupported_version", "unsupported_version"),
                            ("executable_missing", "executable_missing"),
                            ("process_failed", "process_failed"),
                            ("timeout", "timeout"),
                            ("invalid_response", "invalid_response"),
                            ("stale_snapshot", "stale_snapshot"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                ("abstain_reason", models.CharField(blank=True, default="", max_length=24)),
                ("contract_version", models.CharField(max_length=16)),
                ("algorithm_version", models.CharField(max_length=64)),
                ("config_version", models.CharField(max_length=64)),
                ("matcher_build", models.CharField(blank=True, default="", max_length=64)),
                ("candidates", models.JSONField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("due_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lease_token", models.UUIDField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("retrieval_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("ranking_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_runs",
                        to="feedback.report",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                ("score", models.FloatField()),
                ("features", models.JSONField()),
                ("evidence", models.JSONField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.membership",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="feedback.problem",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions",
                        to="matching.matchrun",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.workspace",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="matchrun",
            index=models.Index(
                fields=["workspace", "report", "created_at"], name="match_run_report_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="matchrun",
            index=models.Index(fields=["state", "due_at"], name="match_run_due_idx"),
        ),
        migrations.AddConstraint(
            model_name="matchrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["pending", "running"])),
                fields=("report",),
                name="one_active_match_run_per_report",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("failure", "stale_snapshot"), ("state", "stale")),
                    models.Q(
                        ("state", "failed"),
                        models.Q(("failure", ""), _negated=True),
                        models.Q(("failure", "stale_snapshot"), _negated=True),
                    ),
                    models.Q(
                        models.Q(("state__in", ["failed", "stale"]), _negated=True), ("failure", "")
                    ),
                    _connector="OR",
                ),
                name="match_run_failure_matches_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("state", "abstained"), models.Q(("abstain_reason", ""), _negated=True)
                    ),
                    models.Q(
                        models.Q(("state", "abstained"), _negated=True), ("abstain_reason", "")
                    ),
                    _connector="OR",
                ),
                name="match_run_abstain_reason_matches_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchsuggestion",
            constraint=models.UniqueConstraint(
                fields=("run", "rank"), name="unique_match_suggestion_rank"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchsuggestion",
            constraint=models.UniqueConstraint(
                fields=("run", "problem"), name="unique_match_suggestion_problem"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchsuggestion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("decided_at__isnull", True),
                        ("decided_by__isnull", True),
                        ("decision", "pending"),
                    ),
                    models.Q(
                        models.Q(("decision", "pending"), _negated=True),
                        ("decided_at__isnull", False),
                        ("decided_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="match_suggestion_decision_has_actor",
            ),
        ),
    ]
