# Generated by Django 5.2.17 on 2026-09-27 22:38

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_invitation_one_pending_invitation_per_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("slack", "Slack"), ("github", "GitHub")], max_length=10
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=64)),
                ("identity", models.CharField(blank=True, max_length=200)),
                ("credential", models.TextField(blank=True)),
                ("scopes", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("error", "Needs attention"),
                            ("disconnected", "Disconnected"),
                        ],
                        default="disconnected",
                        max_length=16,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("repository", models.CharField(blank=True, max_length=200)),
                ("repository_id", models.CharField(blank=True, max_length=64)),
                ("visibility", models.CharField(blank=True, max_length=16)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.workspace"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AllowedChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("channel_id", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("is_private", models.BooleanField()),
                ("verified_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="connections.connection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SetupState",
            fields=[
                (
                    "token_digest",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("session_digest", models.CharField(max_length=64)),
                (
                    "provider",
                    models.CharField(
                        choices=[("slack", "Slack"), ("github", "GitHub")], max_length=10
                    ),
                ),
                ("repository", models.CharField(blank=True, max_length=200)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.membership"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="connection",
            constraint=models.UniqueConstraint(
                fields=("workspace", "provider"), name="one_workspace_provider"
            ),
        ),
        migrations.AddConstraint(
            model_name="connection",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("provider", "slack"),
                    models.Q(("external_id", ""), _negated=True),
                    models.Q(("status", "disconnected"), _negated=True),
                ),
                fields=("provider", "external_id"),
                name="one_active_slack_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="allowedchannel",
            constraint=models.UniqueConstraint(
                fields=("connection", "channel_id"), name="unique_allowed_channel"
            ),
        ),
    ]
