# Generated by Django 5.2.17 on 2026-09-27 23:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubWebhookReceipt",
            fields=[
                ("delivery_id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
