# Generated by Django 5.2.17 on 2026-09-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0002_githubwebhookreceipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="binding_revision",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
