# Generated by Django 5.2.17 on 2026-10-01 18:39

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_invitation_one_pending_invitation_per_email"),
        ("connections", "0002_github_issue_lifecycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackLinkCode",
            fields=[
                (
                    "token_digest",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.membership"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("slack", "Slack"), ("github", "GitHub")], max_length=10
                    ),
                ),
                ("provider_team_id", models.CharField(max_length=64)),
                ("provider_user_id", models.CharField(max_length=64)),
                ("linked_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.membership"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.workspace"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "provider", "provider_team_id", "provider_user_id"),
                        name="unique_external_identity",
                    ),
                    models.UniqueConstraint(
                        fields=("membership", "provider"), name="one_identity_per_membership"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SlackCaptureContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("team_id", models.CharField(max_length=64)),
                ("channel_id", models.CharField(max_length=64)),
                ("actor_id", models.CharField(max_length=64)),
                ("message_ts", models.CharField(max_length=64)),
                ("thread_ts", models.CharField(blank=True, max_length=64)),
                ("author_external_id", models.CharField(blank=True, max_length=64)),
                ("text", models.TextField(blank=True)),
                ("link_required", models.BooleanField(default=False)),
                ("channel_validated_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_reason", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="connections.connection"
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["expires_at"], name="capture_context_expiry_idx")],
            },
        ),
    ]
