# Generated by Django 5.2.17 on 2026-09-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0003_connection_binding_revision"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="reconciliation_binding_revision",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="connection",
            name="reconciliation_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connection",
            name="reconciliation_targets",
            field=models.JSONField(default=list),
        ),
    ]
