# Generated by Django 5.2.17 on 2026-09-28 22:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0004_connection_reconciliation_binding_revision_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GitHubWebhookReceipt",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="reconciliation_binding_revision",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="reconciliation_started_at",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="reconciliation_targets",
        ),
    ]
