# Generated by Django 5.2.17 on 2026-09-22 21:52

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_invitation_one_pending_invitation_per_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("fix_available", "Fix available"),
                            ("not_planned", "Not planned"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("not_planned_reason", models.TextField(blank=True, default="")),
                ("resolution_revision", models.PositiveIntegerField(default=0)),
                ("fix_note", models.TextField(blank=True, default="")),
                ("fix_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("needs_review", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "fix_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.membership",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_problems",
                        to="accounts.membership",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problems",
                        to="accounts.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("customer_label", models.CharField(blank=True, default="", max_length=200)),
                (
                    "customer_contact_reference",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("affected_version", models.CharField(blank=True, default="", max_length=100)),
                (
                    "triage_state",
                    models.CharField(
                        choices=[("new", "New"), ("linked", "Linked"), ("dismissed", "Dismissed")],
                        default="new",
                        max_length=12,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_reports",
                        to="accounts.membership",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="feedback.problem",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_reports",
                        to="accounts.membership",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="accounts.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("manual", "Manual"), ("slack", "Slack")], max_length=12
                    ),
                ),
                ("external_workspace_id", models.CharField(blank=True, default="", max_length=64)),
                ("external_channel_id", models.CharField(blank=True, default="", max_length=64)),
                ("external_message_id", models.CharField(blank=True, default="", max_length=64)),
                ("permalink", models.URLField(blank=True, default="", max_length=500)),
                ("author_external_id", models.CharField(blank=True, default="", max_length=64)),
                ("author_display_name", models.CharField(blank=True, default="", max_length=200)),
                ("snapshot_text", models.TextField(blank=True, default="")),
                ("captured_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source",
                        to="feedback.report",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_sources",
                        to="accounts.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actor_system", models.CharField(blank=True, default="", max_length=32)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("report.created", "Report created"),
                            ("report.updated", "Report updated"),
                            ("report.assigned", "Report assigned"),
                            ("report.linked", "Report linked"),
                            ("report.unlinked", "Report unlinked"),
                            ("report.dismissed", "Report dismissed"),
                            ("report.restored", "Report restored"),
                            ("problem.created", "Problem created"),
                            ("problem.updated", "Problem updated"),
                            ("problem.state_changed", "Problem state changed"),
                            ("problem.fix_confirmed", "Problem fix confirmed"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[("report", "Report"), ("problem", "Problem")], max_length=10
                    ),
                ),
                ("record_id", models.UUIDField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.membership",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workspace", "record_type", "record_id", "created_at"],
                        name="activity_record_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("actor_membership__isnull", False), ("actor_system", "")),
                            models.Q(
                                ("actor_membership__isnull", True),
                                models.Q(("actor_system", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="activity_exactly_one_actor",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(fields=["workspace", "state"], name="problem_ws_state_idx"),
        ),
        migrations.AddConstraint(
            model_name="problem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "not_planned"), _negated=True),
                    models.Q(("not_planned_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="problem_not_planned_reason_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="problem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "fix_available"), _negated=True),
                    ("resolution_revision__gte", 1),
                    _connector="OR",
                ),
                name="problem_fix_revision_required",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["workspace", "triage_state", "created_at"],
                name="report_ws_triage_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["workspace", "assignee"], name="report_ws_assignee_idx"),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["workspace", "problem"], name="report_ws_problem_idx"),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("problem__isnull", False), ("triage_state", "linked")),
                    models.Q(
                        models.Q(("triage_state", "linked"), _negated=True),
                        ("problem__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="report_link_state_matches_problem",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportsource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "manual"), _negated=True),
                fields=(
                    "workspace",
                    "kind",
                    "external_workspace_id",
                    "external_channel_id",
                    "external_message_id",
                ),
                name="unique_external_report_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("external_channel_id", ""),
                        ("external_message_id", ""),
                        ("external_workspace_id", ""),
                        ("kind", "manual"),
                    ),
                    models.Q(
                        models.Q(("kind", "manual"), _negated=True),
                        models.Q(("external_workspace_id", ""), _negated=True),
                        models.Q(("external_channel_id", ""), _negated=True),
                        models.Q(("external_message_id", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="report_source_external_ids_match_kind",
            ),
        ),
    ]
