# Generated by Django 5.2.17 on 2026-09-27 18:50

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_invitation_one_pending_invitation_per_email"),
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportNotificationOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("resolution_revision", models.PositiveIntegerField()),
                ("report_version", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("failed", "Failed"),
                            ("uncertain", "Uncertain"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("remote_conversation_id", models.CharField(blank=True, default="", max_length=64)),
                ("remote_message_id", models.CharField(blank=True, default="", max_length=64)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invalidation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("reassigned", "Report reassigned"),
                            ("moved", "Report moved to another problem"),
                            ("unlinked", "Report ungrouped"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="feedback.problem",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.membership",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification_operations",
                        to="feedback.report",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_notification_operations",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workspace", "report", "state"], name="notification_ws_report_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("sent_at__isnull", False),
                                ("state", "sent"),
                                models.Q(("remote_conversation_id", ""), _negated=True),
                                models.Q(("remote_message_id", ""), _negated=True),
                            ),
                            models.Q(
                                models.Q(("state", "sent"), _negated=True),
                                ("sent_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="notification_sent_has_remote_result",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("invalidated_at__isnull", True), ("invalidation_reason", "")),
                            models.Q(
                                ("invalidated_at__isnull", False),
                                models.Q(("invalidation_reason", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="notification_invalidation_complete",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("invalidated_at__isnull", False), ("state", "cancelled")),
                            ("state", "uncertain"),
                            models.Q(
                                models.Q(("state__in", ["cancelled", "uncertain"]), _negated=True),
                                ("invalidated_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="notification_invalidation_matches_state",
                    ),
                ],
            },
        ),
    ]
