# Generated by Django 5.2.17 on 2026-09-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_invitation_one_pending_invitation_per_email"),
        ("feedback", "0002_report_notification_operation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportsource",
            name="submission_key",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="reportsource",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "manual"), ("submission_key__isnull", False)),
                fields=("workspace", "submission_key"),
                name="unique_manual_report_submission",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind", "manual"), ("submission_key__isnull", True), _connector="OR"
                ),
                name="submission_key_only_for_manual",
            ),
        ),
    ]
