# Generated by Django 5.2.17 on 2026-09-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0003_manual_submission_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="action",
            field=models.CharField(
                choices=[
                    ("report.deleted", "Report deleted"),
                    ("report.created", "Report created"),
                    ("report.updated", "Report updated"),
                    ("report.assigned", "Report assigned"),
                    ("report.linked", "Report linked"),
                    ("report.unlinked", "Report unlinked"),
                    ("report.dismissed", "Report dismissed"),
                    ("report.restored", "Report restored"),
                    ("problem.created", "Problem created"),
                    ("problem.updated", "Problem updated"),
                    ("problem.state_changed", "Problem state changed"),
                    ("problem.fix_confirmed", "Problem fix confirmed"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="reportnotificationoperation",
            name="invalidation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("disconnected", "Connection disconnected"),
                    ("reassigned", "Report reassigned"),
                    ("moved", "Report moved to another problem"),
                    ("unlinked", "Report ungrouped"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
