# Generated by Django 5.2.17 on 2026-09-27 23:23

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_invitation_one_pending_invitation_per_email"),
        ("connections", "0001_initial"),
        ("feedback", "0004_alter_activity_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="action",
            field=models.CharField(
                choices=[
                    ("report.deleted", "Report deleted"),
                    ("report.created", "Report created"),
                    ("report.updated", "Report updated"),
                    ("report.assigned", "Report assigned"),
                    ("report.linked", "Report linked"),
                    ("report.unlinked", "Report unlinked"),
                    ("report.dismissed", "Report dismissed"),
                    ("report.restored", "Report restored"),
                    ("problem.created", "Problem created"),
                    ("problem.updated", "Problem updated"),
                    ("problem.state_changed", "Problem state changed"),
                    ("problem.fix_confirmed", "Problem fix confirmed"),
                    ("engineering_issue.linked", "Engineering issue linked"),
                    ("engineering_issue.created", "Engineering issue created"),
                    ("engineering_issue.unlinked", "Engineering issue unlinked"),
                ],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="EngineeringIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("repository_id", models.CharField(max_length=64)),
                ("issue_id", models.CharField(max_length=64)),
                ("number", models.PositiveIntegerField()),
                ("url", models.URLField(max_length=500)),
                ("title", models.CharField(max_length=256)),
                (
                    "state",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")], max_length=10
                    ),
                ),
                ("state_reason", models.CharField(blank=True, default="", max_length=32)),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("access_lost", "Access lost"),
                            ("suspended", "Suspended"),
                            ("deleted", "Deleted"),
                        ],
                        default="ok",
                        max_length=16,
                    ),
                ),
                ("provider_updated_at", models.DateTimeField()),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("sync_error", models.CharField(blank=True, default="", max_length=200)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("unlinked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connections.connection",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.membership",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="engineering_issues",
                        to="feedback.problem",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engineering_issues",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["workspace", "active"], name="eng_issue_ws_active_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("problem",),
                        name="one_active_issue_per_problem",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("workspace", "repository_id", "issue_id"),
                        name="one_active_problem_per_issue",
                    ),
                ],
            },
        ),
    ]
