# Generated by Django 5.2.17 on 2026-09-28 22:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_invitation_one_pending_invitation_per_email"),
        ("connections", "0002_github_issue_lifecycle"),
        ("feedback", "0004_alter_activity_action_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="action",
            field=models.CharField(
                choices=[
                    ("report.deleted", "Report deleted"),
                    ("report.created", "Report created"),
                    ("report.updated", "Report updated"),
                    ("report.assigned", "Report assigned"),
                    ("report.linked", "Report linked"),
                    ("report.unlinked", "Report unlinked"),
                    ("report.dismissed", "Report dismissed"),
                    ("report.restored", "Report restored"),
                    ("problem.created", "Problem created"),
                    ("problem.updated", "Problem updated"),
                    ("problem.state_changed", "Problem state changed"),
                    ("problem.fix_confirmed", "Problem fix confirmed"),
                    ("engineering_issue.linked", "Engineering issue linked"),
                    ("engineering_issue.created", "Engineering issue created"),
                    ("engineering_issue.unlinked", "Engineering issue unlinked"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="reportnotificationoperation",
            name="invalidation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("disconnected", "Connection disconnected"),
                    ("reassigned", "Report reassigned"),
                    ("moved", "Report moved to another problem"),
                    ("unlinked", "Report ungrouped"),
                    ("issue_reopened", "Linked GitHub issue reopened"),
                    ("issue_relinked", "GitHub issue link replaced"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="EngineeringIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("repository_id", models.CharField(max_length=64)),
                ("issue_id", models.CharField(max_length=64)),
                ("number", models.PositiveIntegerField()),
                ("url", models.URLField(max_length=500)),
                ("title", models.CharField(max_length=256)),
                (
                    "state",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")], max_length=10
                    ),
                ),
                ("state_reason", models.CharField(blank=True, default="", max_length=32)),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("inaccessible", "Inaccessible"),
                            ("disconnected", "Disconnected"),
                            ("access_lost", "Access lost"),
                            ("suspended", "Suspended"),
                            ("deleted", "Deleted"),
                        ],
                        default="ok",
                        max_length=16,
                    ),
                ),
                ("provider_updated_at", models.DateTimeField()),
                ("last_attempted_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_successful_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection_installation_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("last_applied_reopen_event_at", models.DateTimeField(blank=True, null=True)),
                ("sync_lease_token", models.UUIDField(blank=True, null=True)),
                ("sync_lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("sync_requested_generation", models.PositiveBigIntegerField(default=0)),
                ("sync_completed_generation", models.PositiveBigIntegerField(default=0)),
                ("sync_attempts", models.PositiveIntegerField(default=0)),
                ("sync_retry_at", models.DateTimeField(blank=True, null=True)),
                ("sync_error", models.CharField(blank=True, default="", max_length=200)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("unlinked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="connections.connection",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.membership",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="engineering_issues",
                        to="feedback.problem",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engineering_issues",
                        to="accounts.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssueReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("binding_revision", models.PositiveIntegerField()),
                (
                    "connection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="connections.connection"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssueReconciliationTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("generation", models.PositiveBigIntegerField()),
                ("done", models.BooleanField(default=False)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="feedback.engineeringissue"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="feedback.issuereconciliation",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="engineeringissue",
            index=models.Index(fields=["workspace", "active"], name="eng_issue_ws_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="engineeringissue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("problem",),
                name="one_active_issue_per_problem",
            ),
        ),
        migrations.AddConstraint(
            model_name="engineeringissue",
            constraint=models.UniqueConstraint(
                fields=("workspace", "issue_id"), name="one_problem_per_github_issue"
            ),
        ),
        migrations.AddConstraint(
            model_name="issuereconciliationtarget",
            constraint=models.UniqueConstraint(
                fields=("run", "issue"), name="unique_issue_reconcile_target"
            ),
        ),
    ]
