# Generated by Django 5.2.17 on 2026-09-30 12:37

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_invitation_one_pending_invitation_per_email"),
        ("feedback", "0005_engineering_issues"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="fix_evidence_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="problem",
            name="fix_version",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("resolution_revision", models.PositiveIntegerField()),
                ("report_version", models.PositiveIntegerField()),
                (
                    "contact_state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("contacted", "Contacted"),
                            ("confirmed", "Confirmed"),
                            ("still_affected", "Still affected"),
                            ("no_response", "No response"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("outcome_note", models.TextField(blank=True, default="")),
                ("outcome_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_follow_ups",
                        to="accounts.membership",
                    ),
                ),
                (
                    "outcome_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_follow_ups",
                        to="accounts.membership",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="follow_ups",
                        to="feedback.problem",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="follow_ups",
                        to="accounts.membership",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="follow_ups",
                        to="feedback.report",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workspace", "contact_state"], name="followup_ws_state_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("report", "resolution_revision"),
                        name="one_follow_up_per_report_revision",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("contact_state", "pending"),
                                ("outcome_at__isnull", True),
                                ("outcome_by__isnull", True),
                            ),
                            models.Q(
                                models.Q(("contact_state", "pending"), _negated=True),
                                ("outcome_at__isnull", False),
                                ("outcome_by__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="follow_up_outcome_has_actor_and_time",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("contact_state", "no_response"), _negated=True),
                            models.Q(("outcome_note", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="follow_up_no_response_requires_note",
                    ),
                ],
            },
        ),
    ]
