# Generated by Django 5.2.17 on 2026-09-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0005_alter_activity_action_engineeringissue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportnotificationoperation",
            name="invalidation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("disconnected", "Connection disconnected"),
                    ("reassigned", "Report reassigned"),
                    ("moved", "Report moved to another problem"),
                    ("unlinked", "Report ungrouped"),
                    ("issue_reopened", "Linked GitHub issue reopened"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
