# Generated by Django 5.2.17 on 2026-09-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0006_alter_reportnotificationoperation_invalidation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="engineeringissue",
            name="connection_binding_revision",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="engineeringissue",
            name="last_applied_reopen_event_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="engineeringissue",
            name="last_attempted_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="engineeringissue",
            name="last_successful_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="engineeringissue",
            name="sync_completed_generation",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="engineeringissue",
            name="sync_lease_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="engineeringissue",
            name="sync_lease_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="engineeringissue",
            name="sync_requested_generation",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
