# Generated by Django 5.2.17 on 2026-10-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_invitation_one_pending_invitation_per_email"),
        ("feedback", "0006_problem_fix_evidence_url_problem_fix_version_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="followup",
            name="one_follow_up_per_report_revision",
        ),
        migrations.AddConstraint(
            model_name="followup",
            constraint=models.UniqueConstraint(
                fields=("report", "problem", "resolution_revision"),
                name="one_follow_up_per_report_revision",
            ),
        ),
    ]
