# Generated by Django 5.2.17 on 2026-10-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0007_scope_follow_up_revision_to_problem"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportsource",
            name="permalink_attempted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reportsource",
            name="permalink_error",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
