# Generated by Django 5.2.17 on 2026-09-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_invitation_one_pending_invitation_per_email"),
        ("connections", "0003_connection_binding_revision"),
        ("feedback", "0007_engineeringissue_connection_binding_revision_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="engineeringissue",
            name="one_active_problem_per_issue",
        ),
        migrations.AlterField(
            model_name="reportnotificationoperation",
            name="invalidation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("disconnected", "Connection disconnected"),
                    ("reassigned", "Report reassigned"),
                    ("moved", "Report moved to another problem"),
                    ("unlinked", "Report ungrouped"),
                    ("issue_reopened", "Linked GitHub issue reopened"),
                    ("issue_relinked", "GitHub issue link replaced"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="engineeringissue",
            constraint=models.UniqueConstraint(
                fields=("workspace", "issue_id"), name="one_problem_per_github_issue"
            ),
        ),
    ]
