# Generated by Django 5.2.17 on 2026-09-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0008_remove_engineeringissue_one_active_problem_per_issue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="engineeringissue",
            name="connection_installation_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="engineeringissue",
            name="access",
            field=models.CharField(
                choices=[
                    ("ok", "OK"),
                    ("inaccessible", "Inaccessible"),
                    ("disconnected", "Disconnected"),
                    ("access_lost", "Access lost"),
                    ("suspended", "Suspended"),
                    ("deleted", "Deleted"),
                ],
                default="ok",
                max_length=16,
            ),
        ),
    ]
