# Generated by Django 5.2.17 on 2026-09-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0009_engineeringissue_connection_installation_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="engineeringissue",
            name="sync_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="engineeringissue",
            name="sync_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
