# Generated by Django 5.2.17 on 2026-10-08 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_workspace_is_demo"),
        ("feedback", "0009_follow_up_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="action",
            field=models.CharField(
                choices=[
                    ("report.deleted", "Report deleted"),
                    ("report.created", "Report created"),
                    ("report.updated", "Report updated"),
                    ("report.assigned", "Report assigned"),
                    ("report.linked", "Report linked"),
                    ("report.unlinked", "Report unlinked"),
                    ("report.dismissed", "Report dismissed"),
                    ("report.restored", "Report restored"),
                    ("problem.created", "Problem created"),
                    ("problem.updated", "Problem updated"),
                    ("problem.state_changed", "Problem state changed"),
                    ("problem.fix_confirmed", "Problem fix confirmed"),
                    ("problem.fix_release_linked", "Problem release linked"),
                    ("problem.fix_release_unlinked", "Problem release unlinked"),
                    ("engineering_issue.linked", "Engineering issue linked"),
                    ("engineering_issue.created", "Engineering issue created"),
                    ("engineering_issue.unlinked", "Engineering issue unlinked"),
                    ("follow_up.notification_approved", "Notification approved"),
                    ("follow_up.notification_sent", "Notification sent"),
                    ("follow_up.notification_failed", "Notification failed"),
                    ("follow_up.notification_cancelled", "Notification cancelled"),
                    ("follow_up.outcome_recorded", "Outcome recorded"),
                    ("follow_up.outcome_corrected", "Outcome corrected"),
                    ("follow_up.recipient_changed", "Recipient changed"),
                ],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="FixRelease",
            fields=[
                (
                    "problem",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="fix_release",
                        serialize=False,
                        to="feedback.problem",
                    ),
                ),
                ("provider", models.CharField(choices=[("github", "GitHub")], max_length=16)),
                ("external_id", models.CharField(max_length=64)),
                ("repository_id", models.CharField(max_length=64)),
                ("tag_name", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=500)),
                ("published_at", models.DateTimeField()),
                ("linked_at", models.DateTimeField()),
                (
                    "linked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.membership",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.workspace"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("tag_name", ""), _negated=True),
                            models.Q(("url", ""), _negated=True),
                        ),
                        name="fix_release_tag_url_nonempty",
                    )
                ],
            },
        ),
    ]
