# Generated by Django 5.2.17 on 2026-09-28 22:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0005_delete_githubwebhookreceipt_and_more"),
        ("feedback", "0010_engineeringissue_sync_attempts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="engineeringissue",
            name="connection_binding_revision",
        ),
        migrations.RemoveField(
            model_name="engineeringissue",
            name="last_synced_at",
        ),
        migrations.CreateModel(
            name="IssueReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("binding_revision", models.PositiveIntegerField()),
                (
                    "connection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="connections.connection"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssueReconciliationTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("generation", models.PositiveBigIntegerField()),
                ("done", models.BooleanField(default=False)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="feedback.engineeringissue"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="feedback.issuereconciliation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "issue"), name="unique_issue_reconcile_target"
                    )
                ],
            },
        ),
    ]
